#!/usr/bin/env python3

import sys
import argparse

if len(sys.argv) < 2:
    sys.exit(0)

parser = argparse.ArgumentParser(description="Convert X.509 PEM encoded certificates JSON with newlines ('\\n') escaped.")
parser.add_argument('pem_files', metavar='PEM', type=str, nargs='*', help='a PEM file to convert to JSON')
args = parser.parse_args()
pem = args.pem_files

# Read in PEM, replacing newlines with literal '\n' characters
pemList = []
for arg in sys.argv[1:]:
    with open(arg, 'r') as f:
        pem = ""
        for line in f:
            pem += line.replace('\n', '\\n')
        pemList.append(pem)

# Output as a JSON list
count = len(pemList)
if count > 1:
    print("[")
for pem in pemList:
    if count > 1:
        print("\t", end='')
    if pem == pemList[len(pemList)-1]:
        print(f'"{pem}"')
    else:
        print(f'"{pem}",')

if count > 1:
    print("]")
