#!/bin/bash

usage() {
	echo "Usage: csv2json <filepath>"
}

if [[ $# != 2 ]]; then
	usage
	exit 1
fi

if [[ "$1" == "" ]]; then
	usage
	exit 1
fi

jq -cR 'split(",")' "$1" | jq -sf "$HOME/.bin/csv2json-helper.jq"
