#!/bin/bash

set -e

if [ "$#" -ne 1 ]; then
	echo "usage: $0 <path>"
	exit 1
fi

PEM=$(cat "$1")

if [[ "${PEM:0:1}" == '"' ]] && [[ "${PEM: -1}" == '"' ]]; then
	# Remove first character '"'
	PEM="${PEM:1}"
	# Remove last character '"'
	PEM="${PEM%?}"
fi
# Convert escaped newlines to real newlines
printf -- "${PEM//\\n/$'\n'}"
