#!/bin/bash

base=(
# Operating System
zsh
lsof
man-db
man-pages
gnupg2
util-linux
stow
zip
pv
jq

# Optical Media
dvdbackup
k3b
dvd+rw-tools

# Software Engineering

## Tools
neovim
git
fzf
plotutils
gnuplot

## Debuggers
gdb
delve
valgrind

## Documentation
texlive

## Compiler Toolchains
make
gcc
clang
golang
clojure

# Internet Utilities
wget
curl
nmap
tcpdump
traceroute
bind-utils

# Media Utilities
mupdf
gimp
)

sudo dnf install "${base[@]}"
go install golang.org/x/tools/gopls@latest
