#!/bin/bash

base=(
# Operating System
zsh
lsof
man-db
man-pages
gnupg2
util-linux
stow
pv
jq

# Optical Media
dvdbackup
k3b
dvd+rw-tools

# Programming Development Tools
git
fzf
golang
texlive
neovim
clang
gcc
make
clojure
gdb
delve
zip
valgrind

# Internet Utilities
wget
curl
nmap
tcpdump
traceroute
bind-utils

# Media Utilities
mupdf

# Game Development Tools
gimp
)

sudo dnf install "${base[@]}"
go install golang.org/x/tools/gopls@latest
